---
language: ruby
bundler_args: --without system_tests --path=vendor --full-index
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.10"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5.3"
